package Task11;



//Qn-6
When we compare the entered password with the actual password. If they don't match, we explicitly throw a custom exception with an appropriate error message.

Within the try block, if the passwords don't match, the throw statement throws an instance of Custom Exception with the specified error message. The program then jumps to the catch block where the exception is caught, and we can handle it appropriately. In this case, we simply print the error message. 


